### ISSUE TITLE
No link back to repository in the website

### ISSUE THREAD

**Issue by DipanshKhandelwal** [sugarlabs/sugar-web-samples#4]
Once we are on the html page of the repository, there is no link back to the GitHub repository.

**Comment by quozl** [comment]
By the same argument, there should be a link back from each sample.

Meanwhile, a handy workaround is a browser back button.

Proposed change in #5 gives GitHub unfair prominence; perhaps also a Sugar Labs link is needed.

**Comment by DipanshKhandelwal** [comment]
@quozl yes, sugar labs link is a good idea to add,  but where should it point to ? The documentation , the sugarlabs website or its github page?
Yes #5 gives Github prominence , but I actually added it in a way so that anyone could see and contribute to this web-samples.

**Comment by quozl** [comment]
Should point to https://sugarlabs.org/, thanks.

Interesting that you think contributions would be needed.

https://github.com/sugarlabs/sugar-web-samples is mostly unused and useless at the moment, as it is unmaintained and out of date.  It remains linked from https://developer.sugarlabs.org/ though, so maintenance is welcome.

Critical contribution needed for sugar-web-samples is to resynchronise `lib/sugar-web` with the https://github.com/sugarlabs/sugar-web repository, and test and fix each regression introduced (#6).  Five years of changes, at least, haven't been applied.

Coincidentally, just heard this from my headphones ... "We create a problem to solve because we don't know how to handle the real one." - Setsu Uzume, host of PodCastle episode 498.  Insightful!

**Comment by DipanshKhandelwal** [comment]
@quozl those are some nice words.
Just check it out once -
It points to https://sugarlabs.org/ .
![sl](https://user-images.githubusercontent.com/24923974/34275639-31b1830a-e6c4-11e7-9699-fa3d1a70754d.png)

**Comment by DipanshKhandelwal** [comment]
[Changes in #5 ](https://github.com/sugarlabs/sugar-web-samples/pull/5/commits/dc83f37bb4a5c280028061d2505a076d25168ca1)
